### ISSUE TITLE
Eating CPU immoderately

### ISSUE THREAD

**Issue by hongliliu** [vlas-sokolov/multicube#4]
Dear @keflavich,
         Thanks very much for your many efforts on this program. It would be very useful for me. Actually, I am using it to fit a huge amount of data (~ 1 Gb). However, when I run your code to sometime, there is warning message as below and then I find the program is eating my CPU immoderately so that no more CUP can be used for other work. So, do you have any idea about that problem? Thanks a lot in advance.
         Best regards,
@hongliliu
PS: warning message: WARNING: Selected model is best only for less than %5 of the cube, consider using the map of guesses. [multicube.subcube]
INFO: Overall best model: selected #600 [ 1.91  7.09  0.27] [multicube.subcube]
INFO: Best model @ highest SNR: #442 [ 7.15  5.64  0.62] [multicube.subcube]

**Comment by keflavich** [comment]
This is probably a question for @vlas-sokolov - I think these messages come from multicube, not from pyspeckit

**Comment by hongliliu** [comment]
Many thanks to you @keflavich. 
@vlas-sokolov do you have some suggestions about that problem? Thank all of you so much for the efforts on this program.
Best regards,
@hongli

**Comment by vlas-sokolov** [comment]
Hi @hongliliu, don't worry about that warning message - it only tells that a single guess would not fit every spectrum in your data, and that it's better to pass a map of best guesses (stored as a `best_guesses` attribute) to pyspeckit instead.

Do you know at which point in your code the CPU load increases? Are all the cores used at 100%? If it is after the "INFO" messages are printed, it is probable that you are passing too high a value for the `multicore` parameter when you fit the spectra with pyspeckit. If so, try reducing it so that not all the cores are used.

**Comment by hongliliu** [comment]
Thanks a lot for your explanations @vlas-sokolov. Now I already reduced the number of the core usage. I'll look forward to good results. I don't know at which point the program was eating my full CUP, sorry. 
BTW, could I ask you for how to prepare a map of best guesses, pls. Also, could you in near future give an notebook about how to fit the multi-velocity components, pls. Thank you very very much. 
Best regards,
Hongli

**Comment by vlas-sokolov** [comment]
@hongliliu I'm glad it worked!

For fitting multiple velocity components, you can check [this notebook](https://github.com/vlas-sokolov/multicube/blob/redefined_fiteach/notebooks/gaussian_x2.ipynb) out.
